Repository KEF3-5Trillion/KFE3-bootup-5Trillion, pull requests merged in 2025-06, with the labels that each got.

#15 [chore] @ui/* 경로를 위한 tsconfig path alias 설정 (#14)
  packages/ui/package.json
  packages/ui/tsconfig.json
  pnpm-lock.yaml
Labels: ⚙️ chore

#19 [chore] pnpm-lock.yaml 업데이트 (#18)
  pnpm-lock.yaml
Labels: ⚙️ chore

#21 [⚙️ chore] padding 디자인 토큰 생성 #17
  packages/ui/src/styles/token/spacing.css
Labels: ⚙️ chore

#26 [✨ feat] 바텀시트 컴포넌트 생성과 eslint 설치 및 설정 추가
  eslint.config.mjs
  packages/ui/package.json
  packages/ui/src/components/BottomSheet/BottomSheet.stories.tsx
  packages/ui/src/components/BottomSheet/BottomSheet.tsx
  packages/ui/src/components/BottomSheet/useBottomSheet.ts
  pnpm-lock.yaml
Labels: ✨ feat, ⚙️ chore

#28 [✨ feat] 버튼 컴포넌트 구현
  packages/ui/src/components/BottomSheet/BottomSheet.tsx
  packages/ui/src/components/Button/Button.stories.ts
  packages/ui/src/components/Button/Button.tsx
  packages/ui/src/components/Button/button.css
  packages/ui/src/styles/token/colors/primitive.css
  packages/ui/src/styles/token/colors/semantic.css
Labels: ✨ feat

#29 [✨ design] Notosans 폰트 설정과 페이지 meta 정보 수정 #27
  apps/web/src/app/layout.tsx
Labels: ⚙️ chore, 💅 design

#30 [⚙️ chore] 스토리북 CI/CD 설정 #24
  .github/workflows/chromatic.yml
  .gitignore
  packages/ui/.storybook/preview.ts
  packages/ui/package.json
  pnpm-lock.yaml
  turbo.json
Labels: ⚙️ chore
